"""Change log_timestamp to log_date in FoodLog

Revision ID: 1f487c034e91
Revises: 62f35911b644
Create Date: 2025-04-27 16:03:54.213718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f487c034e91'
down_revision = '62f35911b644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_date', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_food_log_log_timestamp')
        batch_op.create_index(batch_op.f('ix_food_log_log_date'), ['log_date'], unique=False)
        batch_op.drop_column('log_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_food_log_log_date'))
        batch_op.create_index('ix_food_log_log_timestamp', ['log_timestamp'], unique=False)
        batch_op.drop_column('log_date')

    # ### end Alembic commands ###
