"""Add first_name and last_name to User table

Revision ID: 2051a18c35d2
Revises: 616f39028e68
Create Date: 2025-04-26 20:37:09.770906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2051a18c35d2'
down_revision = '616f39028e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_user_firstName')
        batch_op.drop_index('ix_user_lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('firstName', sa.VARCHAR(length=128), nullable=False))
        batch_op.create_index('ix_user_lastName', ['lastName'], unique=False)
        batch_op.create_index('ix_user_firstName', ['firstName'], unique=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
