"""Standardize FoodItem nutrients to per 100g/ml and add defaults (retry)

Revision ID: 51bd03ce7347
Revises: 15fa69d737be
Create Date: 2025-05-04 15:54:40.849851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bd03ce7347'
down_revision = '15fa69d737be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_100', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('protein_per_100', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('fat_per_100', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('carbs_per_100', sa.Float(), server_default='0.0', nullable=False))
        batch_op.alter_column('serving_size',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('serving_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.alter_column('serving_unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('serving_size',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('carbs_per_100')
        batch_op.drop_column('fat_per_100')
        batch_op.drop_column('protein_per_100')
        batch_op.drop_column('calories_per_100')

    # ### end Alembic commands ###
