"""Updata log_date recode ymtimestamp in food_log

Revision ID: 621703b8a113
Revises: 323c3fc2c500
Create Date: 2025-05-10 11:42:30.934501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621703b8a113'
down_revision = '323c3fc2c500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.alter_column('log_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_food_log_log_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.create_index('ix_food_log_log_date', ['log_date'], unique=False)
        batch_op.alter_column('log_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
