"""Add MealType model and update User defaults from main branch

Revision ID: 62f35911b644
Revises: 2051a18c35d2
Create Date: 2025-04-27 15:10:55.815672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f35911b644'
down_revision = '2051a18c35d2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE IF EXISTS meal_type")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_type_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_type_user_id'))

    op.drop_table('meal_type')
    # ### end Alembic commands ###
