"""Align FoodItem model with per_100 nutrient columns

Revision ID: 74ea6db298fd
Revises: 51bd03ce7347
Create Date: 2025-05-04 16:58:50.507835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ea6db298fd'
down_revision = '51bd03ce7347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')
        batch_op.drop_column('carbs')
        batch_op.drop_column('fat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('calories', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('protein', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
