"""Add User, FoodItem, and FoodLog models

Revision ID: f4167bb48e4f
Revises: 
Create Date: 2025-04-20 15:41:11.198038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4167bb48e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(length=20), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_item_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('target_protein', sa.Float(), nullable=True),
    sa.Column('target_fat', sa.Float(), nullable=True),
    sa.Column('target_carbs', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('food_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(), nullable=True),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_consumed', sa.Float(), nullable=False),
    sa.Column('unit_consumed', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_log_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_log_log_timestamp'), ['log_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_log_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_log_meal_type'))
        batch_op.drop_index(batch_op.f('ix_food_log_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_food_log_food_item_id'))

    op.drop_table('food_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_item_name'))
        batch_op.drop_index(batch_op.f('ix_food_item_category'))

    op.drop_table('food_item')
    # ### end Alembic commands ###
